Repository matrix-org/synapse, pull requests merged in 2019-09, with the labels that each got.

#5964 Remove bind_email and bind_msisdn
  changelog.d/5964.feature
  synapse/handlers/register.py
  synapse/replication/http/register.py
  synapse/rest/client/v2_alpha/register.py
Labels: phase:1, privacy-sprint

#5940 [2/2] Allow homeservers to send registration emails | Accepting the verification
  changelog.d/5940.feature
  synapse/handlers/account_validity.py
  synapse/handlers/auth.py
  synapse/push/mailer.py
  synapse/push/pusher.py
  synapse/rest/client/v2_alpha/account.py
  synapse/rest/client/v2_alpha/register.py
Labels: phase:1, privacy-sprint

#5980 Add POST /_matrix/client/r0/account/3pid/unbind (MSC2140)
  changelog.d/5980.feature
  synapse/handlers/identity.py
  synapse/rest/client/v2_alpha/account.py
Labels: phase:1, privacy-sprint

#5892 Switch to using v2 Identity Service APIs other than lookup (MSC 2140)
  changelog.d/5892.misc
  contrib/cmdclient/console.py
  synapse/handlers/identity.py
  synapse/rest/client/v2_alpha/account.py
Labels: phase:1, privacy-sprint

#5987 Allow Synapse to send registration emails + choose Synapse or an external server to handle 3pid validation
  UPGRADE.rst
  changelog.d/5835.feature
  changelog.d/5868.feature
  changelog.d/5875.misc
  changelog.d/5876.feature
  changelog.d/5940.feature
  changelog.d/5969.feature
  contrib/cmdclient/console.py
  docs/sample_config.yaml
  synapse/app/client_reader.py
  synapse/config/emailconfig.py
  synapse/config/registration.py
  synapse/handlers/account_validity.py
  synapse/handlers/auth.py
  synapse/handlers/identity.py
  synapse/push/mailer.py
  synapse/push/pusher.py
  synapse/res/templates/password_reset.html
  synapse/res/templates/password_reset.txt
  synapse/res/templates/password_reset_failure.html
  synapse/res/templates/registration.html
  synapse/res/templates/registration.txt
  synapse/res/templates/registration_failure.html
  synapse/res/templates/registration_success.html
  synapse/rest/__init__.py
  synapse/rest/client/v2_alpha/_base.py
  synapse/rest/client/v2_alpha/account.py
  synapse/rest/client/v2_alpha/register.py
  synapse/rest/client/versions.py
Labels: phase:1, privacy-sprint

#5995 Ensure a sid parameter is passed to bind_threepid
  changelog.d/5995.bugfix
  synapse/handlers/identity.py
Labels: bug

#5934 Censor redactions in DB after a month
  changelog.d/5934.feature
  docs/sample_config.yaml
  synapse/config/server.py
  synapse/storage/events.py
  synapse/storage/schema/delta/56/redaction_censor.sql
  tests/storage/test_redaction.py
Labels: privacy-sprint

#6011 Use account_threepid_delegate for 3pid validation
  changelog.d/6011.feature
  synapse/handlers/auth.py
  synapse/handlers/identity.py
  synapse/rest/client/v2_alpha/account.py
Labels: phase:1, privacy-sprint

#6013 Fix existing v2 identity server calls (MSC2140)
  changelog.d/6013.misc
  synapse/handlers/identity.py
Labels: phase:1, privacy-sprint

#5976 Use the v2 Identity Service API for lookups (MSC2134 + MSC2140)
  changelog.d/5897.feature
  synapse/handlers/identity.py
  synapse/handlers/room.py
  synapse/handlers/room_member.py
  synapse/rest/client/v1/room.py
  synapse/util/hash.py
Labels: phase:1, privacy-sprint

#5997 Fix well-known lookups with the federation certificate whitelist
  changelog.d/5996.bugfix
  synapse/config/tls.py
  synapse/crypto/context_factory.py
  synapse/http/federation/matrix_federation_agent.py
  tests/config/test_tls.py
Labels: release blocker

#5979 v2 3PID Invites (part of MSC2140)
  changelog.d/5979.feature
  synapse/handlers/room_member.py
Labels: phase:1, privacy-sprint

#6049 Add some notes on rolling back to v1.3.1.
  UPGRADE.rst
  changelog.d/6049.doc
Labels: release blocker

#6050 Update the upgrade notes
  UPGRADE.rst
  changelog.d/6050.doc
Labels: release blocker

#6067 Drop support for bind param on POST /account/3pid (MSC2290)
  changelog.d/6067.feature
  synapse/rest/client/v2_alpha/account.py
  sytest-blacklist
Labels: phase:1, privacy-sprint

#6042 Allow HS to send emails when adding an email to the HS
  changelog.d/6042.feature
  docs/sample_config.yaml
  synapse/config/emailconfig.py
  synapse/handlers/identity.py
  synapse/push/mailer.py
  synapse/res/templates/add_threepid.html
  synapse/res/templates/add_threepid.txt
  synapse/res/templates/add_threepid_failure.html
  synapse/res/templates/add_threepid_success.html
  synapse/rest/client/v2_alpha/account.py
  synapse/rest/client/v2_alpha/register.py
  synapse/storage/registration.py
Labels: phase:1, privacy-sprint, release blocker

#6043 Implement MSC2290
  changelog.d/6043.feature
  synapse/handlers/deactivate_account.py
  synapse/handlers/identity.py
  synapse/rest/client/v2_alpha/account.py
  synapse/rest/client/v2_alpha/register.py
  synapse/storage/registration.py
  sytest-blacklist
Labels: phase:1, privacy-sprint, release blocker

#6078 Add POST submit_token endpoint for MSISDN
  changelog.d/6078.feature
  synapse/handlers/identity.py
  synapse/rest/client/v2_alpha/account.py
Labels: phase:1, privacy-sprint

#5972 Add m.require_identity_server to /versions unstable_flags
  changelog.d/5972.misc
  synapse/rest/client/versions.py
Labels: phase:1, privacy-sprint, release blocker

#5974 Add m.id_access_token to /versions unstable_features (MSC2264)
  changelog.d/5974.feature
  synapse/rest/client/versions.py
Labels: phase:1, privacy-sprint, release blocker

#6000 Use the federation blacklist for requests to untrusted Identity Servers
  changelog.d/6000.feature
  docs/sample_config.yaml
  synapse/config/server.py
  synapse/handlers/identity.py
  synapse/handlers/room_member.py
Labels: phase:1, privacy-sprint, release blocker

#6044 Add an unstable feature flag for separate add/bind 3pid APIs
  changelog.d/6044.feature
  synapse/rest/client/versions.py
Labels: phase:1, privacy-sprint, release blocker

#6079 Add submit_url response parameter to msisdn /requestToken
  changelog.d/6079.feature
  docs/sample_config.yaml
  synapse/config/registration.py
  synapse/handlers/identity.py
Labels: phase:1, privacy-sprint

#5884 Enable cleaning up extremities with dummy events
  changelog.d/5884.feature
  synapse/config/server.py
Labels: release blocker

#6089 Move last seen info into devices table
  changelog.d/6089.misc
  synapse/storage/client_ips.py
  synapse/storage/schema/delta/56/devices_last_seen.sql
  tests/storage/test_client_ips.py
Labels: release blocker

#6098 Prune old rows in user_ips tables.
  changelog.d/6098.feature
  docs/sample_config.yaml
  synapse/config/server.py
  synapse/metrics/background_process_metrics.py
  synapse/storage/background_updates.py
  synapse/storage/client_ips.py
  tests/storage/test_client_ips.py
Labels: release blocker

#6053 Fix dummy event insertion consent bug
  changelog.d/6053.bugfix
  synapse/handlers/message.py
  synapse/storage/event_federation.py
  tests/storage/test_cleanup_extrems.py
  tests/storage/test_event_federation.py
Labels: performance, release blocker

#6033 Clarify upgrade notes ahead of 1.4.0 release
  UPGRADE.rst
  changelog.d/6027.doc
Labels: release blocker

#6090 Explicitly log when a homeserver does not have a trusted key server configured
  changelog.d/6090.feature
  docs/sample_config.yaml
  synapse/config/key.py
  synapse/config/server.py
Labels: privacy-sprint, release blocker
