Repository matrix-org/synapse, pull requests merged in 2019-11, with the labels that each got.

#5727 Cross-signing [4/4] -- federation edition
  changelog.d/5727.feature
  synapse/federation/sender/per_destination_queue.py
  synapse/handlers/device.py
  synapse/handlers/e2e_keys.py
  synapse/storage/data_stores/main/devices.py
  tests/handlers/test_typing.py
  tests/storage/test_devices.py
Labels: cross-signing-sprint

#6335 Only do `rc_login` ratelimiting on succesful login.
  changelog.d/6335.bugfix
  synapse/handlers/auth.py
  synapse/rest/client/v1/login.py
Labels: release blocker

#6119 Add User-Interactive Auth to /account/3pid/add
  changelog.d/6119.feature
  synapse/rest/client/v2_alpha/account.py
Labels: phase:2, privacy-sprint
