Repository matrix-org/synapse, pull requests merged in 2020-11, with the labels that each got.

#8729 Fix port script fails when DB has no backfilled events.
  changelog.d/8729.bugfix
  scripts/synapse_port_db
Labels: release blocker

#8726 Enable reconnection in DB pool
  changelog.d/8726.bugfix
  synapse/storage/database.py
Labels: release blocker

#8754 Generalise _maybe_store_room_on_invite
  changelog.d/8754.misc
  synapse/handlers/federation.py
  synapse/replication/http/federation.py
  synapse/storage/databases/main/room.py
Labels: sponsored

#8751 Generalise _locally_reject_invite
  changelog.d/8751.misc
  synapse/handlers/room_member.py
Labels: sponsored

#8731 SAML: allowed clock/time difference from IdP
  changelog.d/8731.misc
  docs/sample_config.yaml
  synapse/config/saml2_config.py
Labels: awaiting changes

#8824 Update example prometheus console
  changelog.d/8824.doc
  contrib/prometheus/consoles/synapse.html
Labels: awaiting changes

#8820 Add a config option to change whether unread push notification counts are per-message or per-room
  changelog.d/8820.feature
  docs/sample_config.yaml
  synapse/config/push.py
  synapse/push/httppusher.py
  synapse/push/push_tools.py
  tests/push/test_http.py
Labels: sponsored
