Repository matrix-org/synapse, pull requests merged in 2020-10, with the labels that each got.

#8447 Fix DB query on startup for negative streams.
  changelog.d/8447.bugfix
  synapse/storage/util/id_generators.py
Labels: release blocker

#8438 Fix bug in remote thumbnail search
  changelog.d/8438.bugfix
  synapse/rest/media/v1/media_storage.py
Labels: release blocker

#8292 Allow ThirdPartyEventRules modules to manipulate public room state
  UPGRADE.rst
  changelog.d/8292.feature
  synapse/events/third_party_rules.py
  synapse/handlers/directory.py
  synapse/handlers/room.py
  synapse/module_api/__init__.py
  tests/module_api/test_api.py
  tests/rest/client/third_party_rules.py
Labels: sponsored

#8467 Fix third-party event modules for `check_visibility_can_be_modified` check
  changelog.d/8467.feature
  synapse/events/third_party_rules.py
  tests/rest/client/test_third_party_rules.py
Labels: sponsored

#8468 Additional tests for third-party event rules
  changelog.d/8468.misc
  synapse/events/third_party_rules.py
  tests/rest/client/test_third_party_rules.py
Labels: sponsored

#8312 Add support for olm fallback keys
  changelog.d/8312.feature
  scripts/synapse_port_db
  synapse/handlers/e2e_keys.py
  synapse/handlers/sync.py
  synapse/rest/client/v2_alpha/sync.py
  synapse/storage/databases/main/end_to_end_keys.py
  synapse/storage/databases/main/schema/delta/58/11fallback.sql
  tests/handlers/test_e2e_keys.py
Labels: sponsored

#8464 Combine `SpamCheckerApi` with the more generic `ModuleApi`.
  changelog.d/8464.misc
  docs/spam_checker.md
  synapse/app/homeserver.py
  synapse/events/spamcheck.py
  synapse/events/third_party_rules.py
  synapse/handlers/auth.py
  synapse/module_api/__init__.py
  synapse/server.py
  synapse/spam_checker_api/__init__.py
  tests/module_api/test_api.py
Labels: sponsored

#8463 Reduce inconsistencies between codepaths for membership and non-membership events.
  changelog.d/8463.misc
  synapse/handlers/message.py
  synapse/handlers/room.py
  synapse/handlers/room_member.py
  tests/handlers/test_register.py
  tests/unittest.py
Labels: sponsored

#8380 Dehydrated devices
  changelog.d/8380.feature
  synapse/handlers/device.py
  synapse/rest/client/v2_alpha/devices.py
  synapse/rest/client/v2_alpha/keys.py
  synapse/storage/databases/main/devices.py
  synapse/storage/databases/main/end_to_end_keys.py
  synapse/storage/databases/main/registration.py
  synapse/storage/databases/main/schema/delta/58/11dehydration.sql
  tests/handlers/test_device.py
Labels: sponsored

#8456 Reduce serialization errors in MultiWriterIdGen
  changelog.d/8456.misc
  synapse/storage/database.py
  synapse/storage/engines/_base.py
  synapse/storage/engines/postgres.py
  synapse/storage/engines/sqlite.py
  synapse/storage/util/id_generators.py
  tests/storage/test_base.py
Labels: release blocker

#8492 Clarify error message when plugin config parsers raise an error
  changelog.d/8492.misc
  synapse/util/module_loader.py
Labels: sponsored

#8479 Allow modules to create and send events into rooms
  changelog.d/8479.feature
  synapse/handlers/message.py
  synapse/module_api/__init__.py
  tests/module_api/test_api.py
  tests/rest/client/test_third_party_rules.py
Labels: sponsored

#8530 Remove racey assertion in MultiWriterIDGenerator
  changelog.d/8530.bugfix
  synapse/storage/util/id_generators.py
Labels: regression, release blocker

#8537 Simplify `_locally_reject_invite`
  changelog.d/8537.misc
  synapse/events/builder.py
  synapse/handlers/message.py
  synapse/handlers/room.py
  synapse/handlers/room_member.py
  tests/handlers/test_message.py
  tests/handlers/test_presence.py
  tests/replication/test_federation_sender_shard.py
  tests/storage/test_redaction.py
Labels: sponsored

#8535 Support modifying event content from ThirdPartyRules modules
  changelog.d/8535.feature
  synapse/events/__init__.py
  synapse/events/third_party_rules.py
  synapse/handlers/federation.py
  synapse/handlers/message.py
  tests/rest/client/test_third_party_rules.py
Labels: sponsored

#8564 Fix modifying events in `ThirdPartyRules` modules
  changelog.d/8564.feature
  synapse/events/builder.py
  synapse/handlers/message.py
Labels: sponsored

#8539 Split admin API for reported events into a detail and a list view
  changelog.d/8539.feature
  docs/admin_api/event_reports.rst
  synapse/rest/admin/__init__.py
  synapse/rest/admin/event_reports.py
  synapse/storage/databases/main/room.py
  tests/rest/admin/test_event_reports.py
Labels: awaiting changes

#8671 Abstract code for stripping room state into a separate method
  changelog.d/8671.misc
  synapse/handlers/message.py
  synapse/storage/databases/main/events_worker.py
Labels: sponsored

#8678 Fix serialisation errors when using third-party event rules.
  changelog.d/8678.bugfix
  synapse/handlers/message.py
  synapse/http/server.py
  synapse/storage/databases/main/censor_events.py
  synapse/storage/databases/main/events.py
  synapse/util/__init__.py
  synapse/util/frozenutils.py
Labels: sponsored

#8559 Optimise createRoom with multiple invites
  changelog.d/8559.misc
  synapse/handlers/room.py
  synapse/handlers/room_member.py
Labels: sponsored
