Repository matrix-org/synapse, pull requests merged in 2020-07, with the labels that each got.

#7761 Back out MSC2625 implementation
  changelog.d/7673.feature
  changelog.d/7716.feature
  changelog.d/7761.feature
  synapse/handlers/sync.py
  synapse/push/bulk_push_rule_evaluator.py
  synapse/push/push_tools.py
  synapse/rest/client/v1/push_rule.py
  synapse/storage/data_stores/main/event_push_actions.py
  synapse/storage/data_stores/main/schema/delta/58/07push_summary_unread_count.sql
  tests/replication/slave/storage/test_events.py
  tests/storage/test_event_push_actions.py
Labels: feature:ftue-notifications

#7771 Fix new metric where we used ms instead of seconds
  changelog.d/7771.misc
  synapse/federation/sender/__init__.py
  synapse/handlers/appservice.py
Labels: release blocker

#7961 Fix error reporting when using `opentracing.trace`
  changelog.d/7961.bugfix
  synapse/logging/opentracing.py
  synapse/logging/scopecontextmanager.py
Labels: release blocker

#7964 Add an option to disable purge in delete room admin API
  changelog.d/7964.feature
  docs/admin_api/rooms.md
  synapse/rest/admin/rooms.py
  tests/rest/admin/test_room.py
Labels: awaiting changes
