Repository matrix-org/synapse, pull requests merged in 2021-02, with the labels that each got.

#9302 Honour ratelimit flag for application services for invite ratelimiting
  changelog.d/9302.bugfix
  synapse/handlers/federation.py
  synapse/handlers/room_member.py
  tests/handlers/test_federation.py
Labels: X-Release-Blocker

#8988 docs: fix simple typo, subequently -> subsequently
  synapse/visibility.py
Labels: z-awaiting changes

#9361 Remove unneeded type constraints on 3rd party protocol lookup responses
  changelog.d/9361.bugfix
  synapse/appservice/api.py
Labels: Sponsored

#9383 Add a config option to prioritise local users in user directory search results
  changelog.d/9383.feature
  docs/sample_config.yaml
  synapse/config/user_directory.py
  synapse/storage/databases/main/user_directory.py
  tests/handlers/test_user_directory.py
Labels: Sponsored

#9402 Be smarter about which hosts to send presence to when processing room joins
  changelog.d/9402.bugfix
  synapse/federation/sender/__init__.py
  synapse/handlers/presence.py
  tests/handlers/test_presence.py
Labels: Sponsored

#9438 Regenerate exact thumbnails if missing
  changelog.d/9438.feature
  synapse/rest/media/v1/media_repository.py
  synapse/rest/media/v1/media_storage.py
  synapse/rest/media/v1/thumbnail_resource.py
  synapse/storage/databases/main/media_repository.py
  tests/rest/media/v1/test_media_storage.py
Labels: P1, T-Enhancement

#9436 SSO: redirect to public URL before setting cookies
  changelog.d/9436.bugfix
  synapse/http/__init__.py
  synapse/rest/client/v1/login.py
  tests/rest/client/v1/test_login.py
  tests/rest/client/v1/utils.py
  tests/rest/client/v2_alpha/test_auth.py
  tests/server.py
Labels: social login
