Repository matrix-org/synapse, pull requests merged in 2021-09, with the labels that each got.

#10697 Populate `rooms.creator` field for easy lookup
  changelog.d/10697.misc
  synapse/api/constants.py
  synapse/handlers/federation.py
  synapse/storage/databases/main/room.py
  synapse/storage/schema/main/delta/63/02populate-rooms-creator.sql
  tests/storage/databases/main/test_room.py
Labels: T-Task

#10556 Fix documentation of directory name for remote thumbnails
  changelog.d/10556.doc
  docs/media_repository.md
Labels: X-Awaiting-Changes

#10743 Fix bug with reusing 'txn' when persisting event.
  changelog.d/10743.bugfix
  synapse/storage/databases/main/events.py
Labels: T-Defect

#10566 Allow room creator to send MSC2716 related events in existing room versions
  changelog.d/10566.feature
  synapse/handlers/federation_event.py
  synapse/handlers/message.py
  synapse/storage/databases/main/events.py
Labels: T-Enhancement

#10839 Rename `/batch_send` query parameter from `?prev_event` to more obvious usage with `?prev_event_id` (MSC2716)
  changelog.d/10839.misc
  synapse/rest/client/room_batch.py
Labels: T-Task

#10877 Ensure `(room_id, next_batch_id)` is unique to avoid cross-talk/conflicts between batches (MSC2716)
  changelog.d/10877.feature
  synapse/handlers/message.py
  synapse/rest/client/room_batch.py
  synapse/storage/databases/main/room_batch.py
Labels: T-Enhancement

#9655 Implement MSC3069: Guest support on whoami
  changelog.d/9655.feature
  synapse/rest/client/account.py
  tests/rest/client/test_account.py
Labels: X-Awaiting-Changes

#10922 Fix getTurnServer response: integer ttl
  changelog.d/10922.bugfix
  synapse/rest/client/voip.py
Labels: z-spec compliance
