Repository matrix-org/synapse, pull requests merged in 2021-04, with the labels that each got.

#9491 Add a Synapse Module for configuring presence update routing
  README.rst
  changelog.d/9491.feature
  docs/presence_router_module.md
  docs/sample_config.yaml
  synapse/app/generic_worker.py
  synapse/config/server.py
  synapse/events/presence_router.py
  synapse/federation/sender/__init__.py
  synapse/handlers/presence.py
  synapse/module_api/__init__.py
  synapse/server.py
  tests/events/test_presence_router.py
  tests/handlers/test_sync.py
  tests/module_api/test_api.py
Labels: Sponsored

#9548 Require AppserviceRegistrationType
  changelog.d/9548.removal
  synapse/api/constants.py
  synapse/rest/client/v2_alpha/register.py
  tests/rest/client/v2_alpha/test_register.py
  tests/test_mau.py
Labels: z-spec compliance

#9900 Fix tight loop handling presence replication.
  changelog.d/9900.bugfix
  synapse/handlers/presence.py
  tests/handlers/test_presence.py
Labels: X-Release-Blocker
