Repository matrix-org/synapse, pull requests merged in 2021-07, with the labels that each got.

#10314 Add upgrade notes about disk space for events migration
  CHANGES.md
  changelog.d/10314.bugfix
  docs/upgrade.md
Labels: X-Release-Blocker

#10303 Handle old staged inbound events
  changelog.d/10303.bugfix
  synapse/federation/federation_server.py
  synapse/storage/databases/main/event_federation.py
Labels: X-Regression, X-Release-Blocker

#10336 Ensure we always drop the federation inbound lock
  changelog.d/10336.bugfix
  synapse/federation/federation_server.py
  synapse/storage/databases/main/lock.py
Labels: X-Release-Blocker

#10421 Remove unused `events_by_room`
  changelog.d/10421.misc
  synapse/storage/databases/main/events.py
Labels: T-Task

#10386 Port the ThirdPartyEventRules module interface to the new generic interface
  changelog.d/10386.removal
  docs/modules.md
  docs/sample_config.yaml
  docs/upgrade.md
  synapse/app/_base.py
  synapse/config/third_party_event_rules.py
  synapse/events/third_party_rules.py
  synapse/handlers/federation.py
  synapse/handlers/message.py
  synapse/handlers/room.py
  synapse/module_api/__init__.py
  tests/rest/client/test_third_party_rules.py
Labels: X-Release-Blocker

#10453 Move dev/ docs to development/
  CONTRIBUTING.md
  changelog.d/10453.doc
  docs/SUMMARY.md
  docs/development/cas.md
  docs/development/git.md
  docs/development/img/git/branches.jpg
  docs/development/img/git/clean.png
  docs/development/img/git/squash.png
  docs/development/saml.md
Labels: z-docs

#10461 Fix an error in the docker workflow
  .github/workflows/docker.yml
  changelog.d/10461.misc
Labels: X-Release-Blocker

#9918 Support MSC2033: Device ID on whoami
  changelog.d/9918.feature
  synapse/rest/client/v2_alpha/account.py
  tests/rest/client/v2_alpha/test_account.py
Labels: Sponsored

#10465 Change release script to update debian changelog for RCs
  changelog.d/10465.misc
  scripts-dev/release.py
Labels: X-Release-Blocker

#10483 Document Complement dev usage
  CONTRIBUTING.md
  changelog.d/10483.doc
Labels: z-docs, z-testing

#10439 Fix backfilled events being rejected for no `state_groups`
  changelog.d/10439.bugfix
  tests/handlers/test_federation.py
Labels: T-Defect, z-federation

#10415 Don’t have Scripts in Modules
  changelog.d/10415.misc
  synapse/_scripts/review_recent_signups.py
  synapse/app/admin_cmd.py
  synapse/app/appservice.py
  synapse/app/client_reader.py
  synapse/app/event_creator.py
  synapse/app/federation_reader.py
  synapse/app/federation_sender.py
  synapse/app/frontend_proxy.py
  synapse/app/generic_worker.py
  synapse/app/homeserver.py
  synapse/app/media_repository.py
  synapse/app/pusher.py
  synapse/app/synchrotron.py
  synapse/app/user_dir.py
  synapse/push/pusherpool.py
  synapse/util/versionstring.py
Labels: X-Awaiting-Changes
