Repository matrix-org/synapse, pull requests merged in 2021-01, with the labels that each got.

#8997 Add some extra notes for getting Synapse running on macOS
  .gitignore
  INSTALL.md
  README.rst
  changelog.d/8997.doc
Labels: docs

#9166 Use the account data handler in additional places.
  changelog.d/9166.feature
  synapse/server_notices/resource_limits_server_notices.py
  synapse/server_notices/server_notices_manager.py
Labels: release blocker

#9204 Bump psycopg2 version
  changelog.d/9204.misc
  synapse/python_dependencies.py
  tox.ini
Labels: X-Release-Blocker

#9210 Fix chain cover update to handle events with duplicate auth events
  changelog.d/9210.bugfix
  synapse/util/iterutils.py
  tests/util/test_itertools.py
Labels: X-Release-Blocker

#9227 Add a note to changelog about redis usage
  CHANGES.md
  changelog.d/9227.misc
  docs/workers.md
Labels: X-Release-Blocker
