Repository matrix-org/synapse, pull requests merged in 2021-12, with the labels that each got.

#9445 Add endpoint to get an event at a given timestamp - MSC3030
  changelog.d/9445.feature
  synapse/config/experimental.py
  synapse/federation/federation_client.py
  synapse/federation/federation_server.py
  synapse/federation/transport/client.py
  synapse/federation/transport/server/__init__.py
  synapse/federation/transport/server/federation.py
  synapse/handlers/federation.py
  synapse/handlers/room.py
  synapse/http/servlet.py
  synapse/rest/client/room.py
  synapse/server.py
  synapse/storage/databases/main/events_worker.py
Labels: T-Enhancement

#11469 Update backward extremity docs to make it clear that it does not indicate whether we have fetched an events' `prev_events`
  changelog.d/11469.doc
  docs/development/room-dag-concepts.md
Labels: z-docs, T-Defect

#11378 Allow guests to send state events
  changelog.d/11378.feature
  synapse/rest/client/room.py
Labels: z-blocked

#11487 Test to ensure we share the same `state_group` across the whole historical batch (MSC2716)
  changelog.d/11487.misc
  tests/rest/client/test_room_batch.py
Labels: z-testing, T-Task

#11243 Allow events to be created with no `prev_events` (MSC2716)
  changelog.d/11243.misc
  synapse/handlers/message.py
  synapse/handlers/room_member.py
  tests/handlers/test_message.py
Labels: T-Enhancement

#11360 Add missing type hints to `synapse.appservice`
  changelog.d/11360.misc
  mypy.ini
  synapse/appservice/__init__.py
  synapse/appservice/api.py
  synapse/appservice/scheduler.py
  synapse/config/appservice.py
  tests/appservice/test_appservice.py
Labels: z-blocked

#11582 Add MSC2716 and MSC3030 to `/versions` -> `unstable_features`
  changelog.d/11582.misc
  synapse/config/experimental.py
  synapse/rest/client/versions.py
Labels: T-Enhancement

#11588 Use mock from standard library
  changelog.d/11588.removal
  setup.py
  tests/storage/test_background_update.py
Labels: X-Release-Blocker
