Repository matrix-org/synapse, pull requests merged in 2021-11, with the labels that each got.

#11128 Add domain specific matching for haproxy config
  changelog.d/11128.doc
  docs/reverse_proxy.md
Labels: X-Awaiting-Changes

#11188 Support sending no `state_events_at_start` in the MSC2716 `/batch_send` endpoint
  changelog.d/11188.bugfix
  synapse/rest/client/room_batch.py
Labels: T-Defect

#11207 Add a linearizer on (appservice, stream) when handling ephemeral events.
  changelog.d/11207.bugfix
  synapse/handlers/appservice.py
  tests/handlers/test_appservice.py
Labels: X-Awaiting-Changes

#11244 Rename to more clear `get_insertion_event_id_by_batch_id` (MSC2716)
  changelog.d/11244.misc
  synapse/handlers/message.py
  synapse/rest/client/room_batch.py
  synapse/storage/databases/main/room_batch.py
Labels: T-Task

#11242 Split out federated PDU retrieval into a non-cached version
  changelog.d/11242.misc
  synapse/federation/federation_client.py
Labels: z-federation, T-Task

#11288 Fix error in thumbnail generation
  changelog.d/11288.bugfix
  synapse/rest/media/v1/thumbnailer.py
Labels: X-Awaiting-Changes

#11303 Move sql file for `remove_deleted_devices_from_device_inbox` into v65
  changelog.d/11303.misc
  synapse/storage/schema/main/delta/65/05remove_deleted_devices_from_device_inbox.sql
Labels: X-Awaiting-Changes, X-Release-Blocker

#11320 change 'Home Server' to one word 'homeserver'
  CHANGES.md
  changelog.d/11320.doc
  docs/ancient_architecture_notes.md
  docs/turn-howto.md
Labels: X-Awaiting-Changes

#11324 Add dedicated admin API for blocking a room
  changelog.d/11324.feature
  docs/admin_api/rooms.md
  synapse/rest/admin/__init__.py
  synapse/rest/admin/rooms.py
  synapse/storage/databases/main/room.py
  tests/rest/admin/test_room.py
Labels: X-Awaiting-Changes

#11265 Prevent historical state from being pushed to an application service via `/transactions` (MSC2716)
  changelog.d/11265.bugfix
  synapse/appservice/api.py
  synapse/handlers/room_batch.py
  synapse/handlers/room_member.py
Labels: z-application-service

#11220 Fix using MSC2716 batch sending with event persistence workers
  changelog.d/11220.bugfix
  synapse/app/generic_worker.py
  synapse/events/snapshot.py
Labels: z-workers, T-Defect

#11417 Refactor `backfilled` into specific behavior function arguments (`_persist_events_and_state_updates`)
  changelog.d/11417.misc
  synapse/storage/databases/main/events.py
  synapse/storage/persist_events.py
Labels: T-Task
