Repository matrix-org/synapse, pull requests merged in 2021-08, with the labels that each got.

#10500 Fix deb build script to set prerelease flag correctly
  changelog.d/10500.misc
  docker/build_debian.sh
Labels: X-Release-Blocker

#10464 Add developer documentation to explain room DAG concepts like `outliers` and `state_groups`
  changelog.d/10464.doc
  docs/SUMMARY.md
  docs/development/room-dag-concepts.md
Labels: z-docs

#10537 Mark all MSC2716 events as historical
  changelog.d/10537.misc
  synapse/rest/client/v1/room.py
Labels: T-Task

#10538 When redacting, keep event fields around that maintain the historical event structure intact (MSC2716)
  changelog.d/10538.feature
  synapse/api/room_versions.py
  synapse/events/utils.py
Labels: T-Enhancement

#10518 Make `PeriodicallyFlushingMemoryHandler` (buffered logging handler which periodically flushes itself) the default logging handler.
  changelog.d/10518.feature
  docker/conf/log.config
  docs/sample_log_config.yaml
  synapse/config/logger.py
Labels: X-Release-Blocker

#10612 Build debs for bookworm
  changelog.d/10612.misc
  scripts-dev/build_debian_packages
Labels: X-Release-Blocker

#10638 Allow modules to run looping call on all instances
  changelog.d/10638.feature
  synapse/module_api/__init__.py
Labels: X-Release-Blocker

#10631 fix broken link to upgrade notes
  UPGRADE.rst
  changelog.d/10631.misc
Labels: X-Release-Blocker

#10628 Mount /_synapse/admin/v1/users/{userId}/media admin API on media workers only
  changelog.d/10628.feature
  docs/upgrade.md
  docs/workers.md
  synapse/rest/admin/__init__.py
  synapse/rest/admin/media.py
  synapse/rest/admin/users.py
Labels: X-Release-Blocker
