Repository matrix-org/synapse, pull requests merged in 2022-09, with the labels that each got.

#13692 Add a schema delta to drop unstable private read receipts.
  changelog.d/13692.removal
  synapse/storage/schema/main/delta/72/05remove_unstable_private_read_receipts.sql
Labels: X-Release-Blocker

#13678 Update docs to make enabling metrics more clear
  changelog.d/13678.doc
  docs/metrics-howto.md
Labels: A-Docs, T-Enhancement

#13701 Clarify `(room_id, event_id)` global uniqueness
  changelog.d/13701.doc
  docs/development/database_schema.md
Labels: A-Docs, T-Enhancement

#13671 Share some metrics between the Prometheus exporter and the phone home stats
  changelog.d/13671.misc
  synapse/app/_base.py
  synapse/app/phone_stats_home.py
  synapse/metrics/common_usage_metrics.py
  synapse/server.py
  tests/test_phone_home.py
Labels: Sponsored

#13647 Remove configuration options for direct TCP replication.
  .github/workflows/tests.yml
  changelog.d/13647.removal
  docs/upgrade.md
  docs/usage/configuration/config_documentation.md
  docs/workers.md
  synapse/app/homeserver.py
  synapse/config/server.py
  synapse/config/workers.py
  synapse/replication/tcp/handler.py
  tests/app/test_openid_listener.py
  tests/test_server.py
  tests/utils.py
Labels: X-Release-Blocker

#13506 Re-introduce the spec compliance fix that removes the unspecced `room_id` field in the `/hierarchy` response.
  changelog.d/13506.bugfix
  synapse/handlers/room_summary.py
Labels: Z-Future-Maintenance

#13730 Instrument `get_metadata_for_events` for tracing
  changelog.d/13730.misc
  synapse/storage/databases/main/state.py
Labels: T-Task, A-Messages-Endpoint

#13729 Strip number suffix from instance name to consolidate services that traces are spread over
  changelog.d/13729.misc
  synapse/logging/opentracing.py
Labels: T-Task

#13761 Tag trace with instance name
  changelog.d/13761.misc
  synapse/api/auth.py
  synapse/logging/opentracing.py
Labels: T-Task

#13766 Make sequence `cache_invalidation_stream_seq` begin at `2`
  changelog.d/13766.bugfix
  synapse/storage/schema/__init__.py
  synapse/storage/schema/main/delta/72/08begin_cache_invalidation_seq_at_2.sql.postgres
Labels: T-Defect

#13589 Keep track when we try and fail to process a pulled event
  changelog.d/13589.feature
  synapse/handlers/federation_event.py
  synapse/storage/databases/main/event_federation.py
  synapse/storage/databases/main/events.py
  synapse/storage/schema/__init__.py
  synapse/storage/schema/main/delta/73/01event_failed_pull_attempts.sql
  tests/handlers/test_federation_event.py
Labels: T-Enhancement, A-Messages-Endpoint

#13801 Be able to correlate timeouts in reverse-proxy layer in front of Synapse (pull request ID from header)
  changelog.d/13801.feature
  docs/reverse_proxy.md
  docs/usage/configuration/config_documentation.md
  synapse/config/server.py
  synapse/http/site.py
Labels: T-Enhancement

#13785 Document common fix of Poetry problems by removing egg-info
  changelog.d/13785.doc
  docs/development/dependencies.md
Labels: A-Docs, T-Enhancement

#13811 Fix Docker build when Rust .so has been build locally first
  .dockerignore
  changelog.d/13811.misc
  docker/Dockerfile
Labels: T-Defect, A-Testing

#13825 Add support to purge rows from MSC2716 and other tables when purging a room
  changelog.d/13825.bugfix
  synapse/storage/databases/main/purge_events.py
  synapse/storage/schema/__init__.py
  synapse/storage/schema/main/delta/73/02room_id_indexes_for_purging.sql
Labels: T-Defect, A-Database

#13768 Port the push rule classes to Rust.
  .rustfmt.toml
  changelog.d/13768.misc
  rust/Cargo.toml
  rust/src/lib.rs
  rust/src/push/base_rules.rs
  rust/src/push/mod.rs
  stubs/synapse/synapse_rust/__init__.pyi
  stubs/synapse/synapse_rust/push.pyi
  synapse/handlers/push_rules.py
  synapse/push/baserules.py
  synapse/push/bulk_push_rule_evaluator.py
  synapse/push/clientformat.py
  synapse/storage/databases/main/push_rule.py
  tests/handlers/test_deactivate_account.py
Labels: A-Push

#13857 Lower minimum rustc version to 1.58.1
  .github/workflows/tests.yml
  changelog.d/13857.misc
  rust/Cargo.toml
Labels: X-Release-Blocker

#13858 Lock rust dependencies
  .dockerignore
  .gitignore
  Cargo.lock
  changelog.d/13858.misc
Labels: X-Release-Blocker

#13866 Fix sdist to include rust build script
  changelog.d/13866.bugfix
  pyproject.toml
Labels: X-Release-Blocker

#13782 Store thread IDs on receipts (implement MSC3771) (redo)
  changelog.d/13782.feature
  synapse/config/experimental.py
  synapse/handlers/receipts.py
  synapse/replication/tcp/client.py
  synapse/replication/tcp/streams/_base.py
  synapse/rest/client/read_marker.py
  synapse/rest/client/receipts.py
  synapse/rest/client/versions.py
  synapse/storage/database.py
  synapse/storage/databases/main/receipts.py
  synapse/types.py
  tests/federation/test_federation_sender.py
  tests/handlers/test_appservice.py
  tests/replication/slave/storage/test_events.py
  tests/replication/tcp/streams/test_receipts.py
  tests/storage/test_event_push_actions.py
  tests/storage/test_receipts.py
Labels: A-Threads

#13855 Fix access token leak to logs from proxyagent
  changelog.d/13855.bugfix
  synapse/http/proxyagent.py
Labels: T-Defect

#13635 Only try to backfill event if we haven't tried before recently
  changelog.d/13635.feature
  synapse/handlers/federation.py
  synapse/storage/databases/main/event_federation.py
  tests/storage/test_event_federation.py
Labels: A-Performance, T-Enhancement, A-Messages-Endpoint

#13818 Update NixOS module URL
  changelog.d/13818.doc
  docs/setup/installation.md
Labels: X-Needs-Sign-Off

#13867 Dockerfile for tests: align comments with current behavior
  changelog.d/13867.misc
  docker/complement/Dockerfile
Labels: A-Testing

#13915 Emphasize the right reasons to use `(room_id, event_id)` in a schema
  changelog.d/13915.doc
  docs/development/database_schema.md
Labels: A-Docs, T-Enhancement

#13879 Limit and filter the number of backfill points to get from the database
  changelog.d/13879.misc
  synapse/handlers/federation.py
  synapse/storage/databases/main/event_federation.py
  tests/storage/test_event_federation.py
Labels: T-Task, A-Messages-Endpoint

#13890 Improve backfill robustness by trying more servers.
  changelog.d/13890.misc
  synapse/handlers/federation.py
Labels: A-Messages-Endpoint

#13838 Implement push rule evaluation in Rust.
  changelog.d/13838.misc
  rust/Cargo.toml
  rust/benches/evaluator.rs
  rust/benches/glob.rs
  rust/build.rs
  rust/src/push/base_rules.rs
  rust/src/push/evaluator.rs
  rust/src/push/mod.rs
  rust/src/push/utils.rs
  stubs/synapse/synapse_rust/push.pyi
  synapse/push/bulk_push_rule_evaluator.py
  synapse/push/httppusher.py
  synapse/push/push_rule_evaluator.py
  tests/push/test_push_rule_evaluator.py
Labels: A-Push

#13936 Fix overflows in /messages backfill calculation
  changelog.d/13936.feature
  synapse/storage/databases/main/event_federation.py
  tests/storage/test_event_federation.py
Labels: A-Messages-Endpoint

#13966 Clarifications in user directory for users who share rooms tracking
  changelog.d/13966.misc
  synapse/handlers/user_directory.py
Labels: A-User-Directory, T-Task
