Repository matrix-org/synapse, pull requests merged in 2022-10, with the labels that each got.

#13960 Fix `get_users_in_room` mis-use in `transfer_room_state_on_room_upgrade`
  changelog.d/13960.misc
  synapse/handlers/room_member.py
Labels: T-Task

#13969 Revert the general exception recording introduced in #13814
  changelog.d/13969.misc
  synapse/handlers/federation_event.py
Labels: A-Messages-Endpoint

#14024 Announce that legacy metric names are deprecated, will be turned off by default in Synapse v1.71.0 and removed altogether in Synapse v1.73.0.
  changelog.d/14024.removal
  docs/metrics-howto.md
  docs/upgrade.md
  docs/usage/configuration/config_documentation.md
  synapse/config/metrics.py
Labels: X-Release-Blocker

#13815 Track when the pulled event signature fails
  changelog.d/13815.feature
  synapse/federation/federation_base.py
  synapse/federation/federation_client.py
  tests/federation/test_federation_client.py
  tests/test_federation.py
Labels: T-Enhancement, A-Messages-Endpoint

#14045 Fix backwards compatibility with upcoming threads schema changes
  changelog.d/14045.misc
  synapse/storage/databases/main/event_push_actions.py
Labels: X-Release-Blocker

#13842 Deprecate the `generate_short_term_login_token` method in favor of an async `create_login_token` method in the Module API.
  changelog.d/13842.removal
  docs/upgrade.md
  synapse/module_api/__init__.py
Labels: X-Release-Blocker

#14080 Pin build-system requirements
  changelog.d/14080.misc
  pyproject.toml
Labels: X-Release-Blocker

#14085 Unpin build-system requirements, but impose an upper-bound
  changelog.d/14085.misc
  pyproject.toml
  synapse/config/repository.py
Labels: X-Release-Blocker

#14097 Indicate what endpoint came back with a JSON response we were unable to parse
  changelog.d/14097.misc
  synapse/http/servlet.py
  tests/http/test_servlet.py
Labels: T-Task

#14129 Fix pinning Rust deps in docker images
  .dockerignore
  changelog.d/14129.bugfix
  docker/Dockerfile
Labels: X-Release-Blocker

#14138 Fix rotating existing notifications in push summary
  changelog.d/14138.bugfix
  synapse/storage/databases/main/event_push_actions.py
Labels: X-Release-Blocker

#14172 Optimise the event_push_backfill_thread_id bg job
  changelog.d/14172.bugfix
  synapse/storage/databases/main/event_push_actions.py
Labels: X-Release-Blocker

#14173 Fix docker build OOMing in CI for arm64 builds
  .github/workflows/docker.yml
  changelog.d/14173.docker
  docker/Dockerfile
Labels: X-Release-Blocker

#13816 Stop getting missing `prev_events` after we already know their signature is invalid
  changelog.d/13816.feature
  synapse/api/errors.py
  synapse/handlers/federation.py
  synapse/handlers/federation_event.py
  synapse/storage/databases/main/event_federation.py
  tests/handlers/test_federation_event.py
  tests/storage/test_event_federation.py
Labels: A-Performance, T-Enhancement, A-Messages-Endpoint

#14095 Add debug logs to figure out why an event was filtered
  changelog.d/14095.misc
  synapse/visibility.py
Labels: T-Task

#14018 Implementation of HTTP 307 response for MSC3886 POST endpoint
  changelog.d/14018.feature
  synapse/config/experimental.py
  synapse/config/server.py
  synapse/handlers/sso.py
  synapse/http/server.py
  synapse/http/site.py
  synapse/rest/__init__.py
  synapse/rest/client/rendezvous.py
  synapse/rest/client/versions.py
  synapse/rest/key/v2/local_key_resource.py
  synapse/rest/synapse/client/new_user_consent.py
  synapse/rest/well_known.py
  tests/logging/test_terse_json.py
  tests/rest/client/test_rendezvous.py
  tests/server.py
  tests/test_server.py
Labels: Sponsored

#10015 Fix hiding devices names over federation
  changelog.d/10015.bugfix
  synapse/storage/databases/main/devices.py
Labels: X-Awaiting-Changes

#14215 Fix MSC3030 `/timestamp_to_event` returning `outliers` that it has no idea whether are near a gap or not
  changelog.d/14215.bugfix
  synapse/storage/databases/main/events_worker.py
  tests/rest/client/test_rooms.py
Labels: T-Defect

#14191 Explain `SynapseError` and `FederationError` better
  changelog.d/14191.doc
  synapse/api/errors.py
  synapse/federation/federation_server.py
Labels: A-Docs, T-Task

#13710 Fix event size checks
  changelog.d/13710.bugfix
  synapse/event_auth.py
Labels: A-Spec-Compliance

#14259 Only build aarch64 wheels for cpython manylinux
  changelog.d/14259.misc
  pyproject.toml
Labels: X-Release-Blocker

#11635 Unified search query syntax using the full-text search capabilities of the underlying DB
  changelog.d/11635.feature
  synapse/storage/databases/main/search.py
  synapse/storage/engines/postgres.py
  synapse/storage/schema/main/delta/73/10_update_sqlite_fts4_tokenizer.py
  tests/storage/test_room_search.py
Labels: T-Enhancement, A-Message-Search

#14301 Fix incorrectly sending authentication tokens to application service as headers
  changelog.d/14301.bugfix
  synapse/appservice/api.py
  tests/appservice/test_api.py
Labels: X-Regression

#14096 Refactor MSC3030 `/timestamp_to_event` to move away from our snowflake pull from `destination` pattern
  changelog.d/14096.misc
  synapse/federation/federation_client.py
  synapse/handlers/federation.py
  synapse/handlers/federation_event.py
  synapse/handlers/room.py
  synapse/util/retryutils.py
  tests/federation/test_federation_client.py
Labels: T-Task

#13958 Check appservice user interest against the local users instead of all users (`get_users_in_room` mis-use)
  changelog.d/13958.bugfix
  docs/upgrade.md
  synapse/appservice/__init__.py
  synapse/storage/databases/main/appservice.py
  synapse/storage/databases/main/roommember.py
  tests/appservice/test_appservice.py
  tests/handlers/test_appservice.py
Labels: A-Application-Service, A-Performance, T-Defect
