Repository matrix-org/synapse, pull requests merged in 2022-03, with the labels that each got.

#11610 Order in-flight state group queries in biggest-first order
  changelog.d/11610.misc
  synapse/storage/databases/state/store.py
  tests/storage/databases/test_state_store.py
Labels: X-Release-Blocker

#12144 Enable MSC3030 Complement tests in Synapse
  .github/workflows/tests.yml
  changelog.d/12144.misc
  scripts-dev/complement.sh
Labels: z-testing, T-Task

#12145 Enable MSC2716 Complement tests in Synapse
  .github/workflows/tests.yml
  changelog.d/12145.misc
  scripts-dev/complement.sh
Labels: z-testing, T-Task

#12129 Don't impose version checks on dev extras at runtime
  changelog.d/12129.misc
  synapse/util/check_dependencies.py
  tests/util/test_check_dependencies.py
Labels: X-Release-Blocker, X-Regression

#11915 Rename various ApplicationServices interested methods
  changelog.d/11915.misc
  synapse/appservice/__init__.py
  synapse/handlers/appservice.py
  synapse/handlers/directory.py
  synapse/handlers/receipts.py
  synapse/handlers/typing.py
  tests/appservice/test_appservice.py
  tests/handlers/test_appservice.py
Labels: A-Application-Service, T-Task

#12166 Relax version guard for packaging
  changelog.d/12166.misc
  synapse/python_dependencies.py
Labels: X-Release-Blocker

#11700 Remove workaround introduced in Synapse v1.50.0rc1 for Mjolnir compatibility. Breaks compatibility with Mjolnir v1.3.1 and earlier.
  changelog.d/11700.removal
  docs/upgrade.md
  synapse/util/__init__.py
Labels: T-Task

#12215 Fix broken background updates when using sqlite with `enable_search` off
  changelog.d/12215.bugfix
  synapse/storage/databases/main/search.py
Labels: X-Release-Blocker

#12265 Tweak copy for sso account details template
  changelog.d/12265.misc
  synapse/res/templates/sso_auth_account_details.html
  synapse/res/templates/sso_auth_account_details.js
  synapse/res/templates/sso_footer.html
Labels: X-Release-Blocker

#12288 Mention the new behaviour on unsafe database locale in the upgrade notes
  changelog.d/12288.misc
  docs/upgrade.md
Labels: X-Release-Blocker

#12083 Refactor `create_new_client_event` to use a new parameter, `state_event_ids`, which accurately describes the usage with MSC2716 instead of abusing `auth_event_ids`
  changelog.d/12083.misc
  synapse/handlers/message.py
  synapse/handlers/room_batch.py
  synapse/handlers/room_member.py
  synapse/rest/client/room_batch.py
Labels: T-Task

#12195 Allow modules to store already existing 3PID associations
  changelog.d/12195.feature
  synapse/module_api/__init__.py
Labels: Sponsored

#12313 Un-revert Jinja2 fix
  changelog.d/12313.misc
  synapse/push/mailer.py
  synapse/python_dependencies.py
Labels: X-Release-Blocker

#12310 Add a configuration to exclude rooms from sync response
  changelog.d/12310.feature
  docs/sample_config.yaml
  synapse/config/server.py
  synapse/handlers/sync.py
  synapse/storage/databases/main/roommember.py
  synapse/storage/databases/main/stream.py
  tests/rest/client/test_sync.py
Labels: Sponsored
