Repository matrix-org/synapse, pull requests merged in 2022-04, with the labels that each got.

#12327 Add a module callback to react to account data changes
  changelog.d/12327.feature
  docs/SUMMARY.md
  docs/modules/account_data_callbacks.md
  docs/modules/writing_a_module.md
  synapse/handlers/account_data.py
  synapse/module_api/__init__.py
  tests/rest/client/test_account_data.py
Labels: Sponsored

#12191 Raise an exception when getting state at an outlier
  changelog.d/12191.misc
  synapse/storage/databases/main/state.py
  synapse/storage/state.py
  tests/handlers/test_federation.py
Labels: T-Defect

#12329 Allow non-member state sent in room batch to resolve for historic events (MSC2716)
  changelog.d/12329.bugfix
  synapse/handlers/room_batch.py
Labels: T-Defect

#12317 Explain how to decipher live and historic pagination tokens
  changelog.d/12317.misc
  synapse/types.py
Labels: A-Docs, T-Task

#12379 Post 1.56.0 release tidy up
  changelog.d/12320.misc
  changelog.d/12379.misc
  synapse/python_dependencies.py
Labels: X-Release-Blocker

#12370 Generate historic pagination token for `/messages` when no `?from` token provided
  changelog.d/12370.bugfix
  synapse/handlers/pagination.py
  synapse/handlers/room.py
  synapse/storage/databases/main/stream.py
  synapse/streams/events.py
  tests/storage/test_stream.py
Labels: T-Defect

#12401 Update changelog to describe changes from #12370 relative to `develop`
  changelog.d/12370.bugfix
  changelog.d/12370.feature
Labels: T-Task

#12345 Clarify that we mark as outliers because we don't have any state for them
  changelog.d/12345.doc
  docs/development/room-dag-concepts.md
Labels: A-Docs, T-Task

#12409 Fix rejecting invites over federation
  changelog.d/12409.misc
  synapse/handlers/sync.py
Labels: X-Release-Blocker

#12280 type docker folder
  changelog.d/12280.misc
  docker/configure_workers_and_start.py
  mypy.ini
Labels: X-Awaiting-Changes

#12439 Workaround pip bug installing latest treq and not-latest twisted from hashes
  changelog.d/12439.misc
  docker/Dockerfile
Labels: X-Release-Blocker

#12319 Fix missing sync events during historical batch imports
  changelog.d/12319.bugfix
  synapse/handlers/message.py
  synapse/handlers/sync.py
  synapse/storage/databases/main/stream.py
  tests/rest/client/test_room_batch.py
Labels: A-Sync, T-Defect

#12213 Prevent a sync request from removing a user's busy presence status
  changelog.d/12213.bugfix
  synapse/handlers/events.py
  synapse/handlers/presence.py
  synapse/rest/client/sync.py
  tests/handlers/test_presence.py
Labels: X-Awaiting-Changes

#12555 Fix sending opentracing contexts to remote servers
  changelog.d/12555.bugfix
  synapse/storage/databases/main/devices.py
Labels: X-Release-Blocker
