Repository matrix-org/synapse, pull requests merged in 2022-05, with the labels that each got.

#12573 Update docker.yml of GitHub Action, use docker/metadata-action
  .github/workflows/docker.yml
  changelog.d/12573.docker
Labels: X-Awaiting-Changes

#12664 Fix docs on how to run specific Complement tests after recent `complement.sh` change
  changelog.d/12664.doc
  docs/development/contributing_guide.md
Labels: A-Docs, T-Defect

#12602 docs(contrib): Add link to documentation in dashboard
  changelog.d/12602.misc
  contrib/grafana/synapse.json
Labels: X-Awaiting-Changes

#12683 Fix `/messages` throwing a 500 when querying for non-existent room
  changelog.d/12683.bugfix
  synapse/handlers/pagination.py
  synapse/storage/databases/main/stream.py
Labels: T-Defect

#12729 Fix bug /sync returning 404
  changelog.d/12729.bugfix
  synapse/storage/databases/main/stream.py
Labels: X-Release-Blocker

#12718 Marker events as state - MSC2716
  changelog.d/12718.feature
  synapse/handlers/federation_event.py
Labels: T-Enhancement

#12855 Add a background job to automatically delete stale devices
  changelog.d/12855.feature
  docs/usage/configuration/config_documentation.md
  synapse/config/server.py
  synapse/handlers/device.py
  synapse/storage/databases/main/devices.py
  tests/rest/client/test_devices.py
Labels: Sponsored

#12832 LockStore: fix acquiring a lock via `LockStore.try_acquire_lock`
  changelog.d/12832.bugfix
  synapse/storage/databases/main/lock.py
  tests/storage/databases/main/test_lock.py
Labels: T-Defect

#12918 Fix import in module_api module and docs on the new check_event_for_spam signature
  changelog.d/12918.bugfix
  docs/modules/spam_checker_callbacks.md
  docs/upgrade.md
  synapse/events/spamcheck.py
  synapse/federation/federation_base.py
  synapse/handlers/message.py
  synapse/module_api/__init__.py
  synapse/spam_checker_api/__init__.py
Labels: X-Release-Blocker

#12732 Add config options for media retention
  changelog.d/12732.feature
  docs/usage/configuration/config_documentation.md
  synapse/config/repository.py
  synapse/rest/media/v1/media_repository.py
  tests/rest/media/test_media_retention.py
Labels: Sponsored
