Repository matrix-org/synapse, pull requests merged in 2022-02, with the labels that each got.

#11215 Send to-device messages to application services
  changelog.d/11215.feature
  synapse/appservice/__init__.py
  synapse/appservice/api.py
  synapse/appservice/scheduler.py
  synapse/config/experimental.py
  synapse/handlers/appservice.py
  synapse/handlers/sync.py
  synapse/notifier.py
  synapse/storage/databases/main/appservice.py
  synapse/storage/databases/main/deviceinbox.py
  synapse/storage/schema/main/delta/68/02_msc2409_add_device_id_appservice_stream_type.sql
  tests/appservice/test_scheduler.py
  tests/handlers/test_appservice.py
  tests/storage/test_appservice.py
Labels: Sponsored

#11655 Add a background database update to purge account data for deactivated users.
  changelog.d/11655.feature
  scripts/synapse_port_db
  synapse/storage/databases/main/account_data.py
  synapse/storage/schema/main/delta/68/03_delete_account_data_for_deactivated_accounts.sql
  tests/handlers/test_deactivate_account.py
Labels: Sponsored

#11892 Add a ratelimiter for 3pid invite
  changelog.d/11892.feature
  docs/sample_config.yaml
  synapse/config/ratelimiting.py
  synapse/handlers/room_member.py
Labels: Sponsored

#11114 Fix historical messages backfilling in random order on remote homeservers (MSC2716)
  changelog.d/11114.bugfix
  synapse/handlers/federation.py
  synapse/handlers/federation_event.py
  synapse/handlers/message.py
  synapse/handlers/room_batch.py
  synapse/handlers/room_member.py
  synapse/rest/client/room_batch.py
  synapse/storage/databases/main/event_federation.py
  synapse/storage/databases/main/events.py
Labels: z-federation, T-Defect

#11854 Add a callback to allow modules to deny 3PID
  changelog.d/11854.feature
  docs/modules/password_auth_provider_callbacks.md
  synapse/handlers/auth.py
  synapse/module_api/__init__.py
  synapse/rest/client/account.py
  synapse/rest/client/register.py
  synapse/util/threepids.py
  tests/handlers/test_password_providers.py
Labels: Sponsored

#11989 Note when unstable MSC3283 prefixes will be removed
  changelog.d/11989.feature
  docs/upgrade.md
Labels: X-Release-Blocker

#12009 Allow modules to set a display name on registration
  changelog.d/12009.feature
  docs/modules/password_auth_provider_callbacks.md
  synapse/handlers/auth.py
  synapse/module_api/__init__.py
  synapse/rest/client/register.py
  tests/handlers/test_password_providers.py
Labels: Sponsored

#12024 Fix 500 error with Postgres when looking backwards with the MSC3030 `/timestamp_to_event` endpoint
  changelog.d/12024.bugfix
  synapse/storage/databases/main/events_worker.py
Labels: T-Defect

#12022 Advertise Matrix 1.2 in `/_matrix/client/versions`
  changelog.d/12022.feature
  synapse/rest/client/versions.py
Labels: z-blocked

#12001 Implement account status endpoints (MSC3720)
  changelog.d/12001.feature
  synapse/config/experimental.py
  synapse/federation/federation_client.py
  synapse/federation/transport/client.py
  synapse/federation/transport/server/__init__.py
  synapse/federation/transport/server/federation.py
  synapse/handlers/account.py
  synapse/rest/client/account.py
  synapse/rest/client/capabilities.py
  synapse/server.py
  tests/rest/client/test_account.py
Labels: Sponsored

#11900 Remove excess condition on `knock->leave` check
  changelog.d/11900.misc
  synapse/event_auth.py
Labels: T-Defect

#12099 Move experimental support for MSC3440 to /versions.
  changelog.d/12099.misc
  synapse/rest/client/capabilities.py
  synapse/rest/client/versions.py
Labels: A-Threads
