Repository matrix-org/synapse, pull requests merged in 2022-08, with the labels that each got.

#13368 Instrument `/messages` for understandable traces in Jaeger
  changelog.d/13368.misc
  synapse/api/auth.py
  synapse/federation/federation_client.py
  synapse/handlers/federation.py
  synapse/handlers/federation_event.py
  synapse/handlers/pagination.py
  synapse/handlers/relations.py
  synapse/storage/controllers/state.py
  synapse/storage/databases/main/stream.py
  synapse/streams/events.py
  synapse/visibility.py
Labels: T-Task

#13408 Fix rooms not being properly excluded from incremental sync
  changelog.d/13408.bugfix
  synapse/handlers/sync.py
  tests/rest/client/test_sync.py
Labels: Sponsored

#13447 synapse-workers docker: copy nginx and redis in from base images
  changelog.d/13447.misc
  docker/Dockerfile-workers
  docker/conf-workers/supervisord.conf.j2
Labels: z-testing

#13452 Fix `@tag_args` being off-by-one (ahead)
  changelog.d/13452.misc
  synapse/logging/opentracing.py
Labels: T-Task

#11897 Mark token-authenticaticated-registration API as not-experimental
  changelog.d/11897.doc
  docs/usage/administration/admin_api/registration_tokens.md
Labels: X-Awaiting-Changes

#13453 Allow use of both `@trace` and `@tag_args` stacked on the same function
  changelog.d/13453.misc
  synapse/logging/opentracing.py
  tests/logging/test_opentracing.py
Labels: T-Task

#13501 Revert 'Remove the unspecced field in the response. (#13365)' to give more time for clients to update.
  changelog.d/13501.misc
  synapse/handlers/room_summary.py
Labels: X-Release-Blocker

#13493 Add viewport directive to HTML templates to optimise for mobile
  changelog.d/13493.misc
  synapse/res/templates/account_previously_renewed.html
  synapse/res/templates/account_renewed.html
  synapse/res/templates/add_threepid.html
  synapse/res/templates/add_threepid_failure.html
  synapse/res/templates/add_threepid_success.html
  synapse/res/templates/auth_success.html
  synapse/res/templates/invalid_token.html
  synapse/res/templates/notice_expiry.html
  synapse/res/templates/notif_mail.html
  synapse/res/templates/password_reset.html
  synapse/res/templates/password_reset_confirmation.html
  synapse/res/templates/password_reset_failure.html
  synapse/res/templates/password_reset_success.html
  synapse/res/templates/recaptcha.html
  synapse/res/templates/registration.html
  synapse/res/templates/registration_failure.html
  synapse/res/templates/registration_success.html
  synapse/res/templates/registration_token.html
  synapse/res/templates/sso_account_deactivated.html
  synapse/res/templates/sso_auth_account_details.html
  synapse/res/templates/sso_auth_bad_user.html
  synapse/res/templates/sso_auth_confirm.html
  synapse/res/templates/sso_auth_success.html
  synapse/res/templates/sso_error.html
  synapse/res/templates/sso_login_idp_picker.html
  synapse/res/templates/sso_new_user_consent.html
  synapse/res/templates/sso_redirect_confirm.html
  synapse/res/templates/terms.html
  synapse/static/client/login/index.html
  synapse/static/client/register/index.html
Labels: X-Awaiting-Changes, z-email-push

#13499 Instrument `FederationStateIdsServlet` - `/state_ids`
  changelog.d/13499.misc
  synapse/federation/federation_server.py
  synapse/handlers/federation.py
  synapse/storage/databases/main/event_federation.py
  synapse/util/ratelimitutils.py
Labels: A-federation, T-Task

#13489 Instrument the federation/backfill part of `/messages`
  changelog.d/13489.misc
  synapse/federation/federation_client.py
  synapse/handlers/federation.py
  synapse/handlers/federation_event.py
  synapse/logging/opentracing.py
  synapse/storage/controllers/persist_events.py
  synapse/storage/controllers/state.py
  synapse/storage/databases/main/event_federation.py
  synapse/storage/databases/main/events.py
  synapse/storage/databases/main/events_worker.py
  synapse/storage/util/partial_state_events_tracker.py
Labels: A-federation, T-Task, A-Messages-Endpoint

#13533 Add specific metric to time long-running `/messages` requests
  changelog.d/13533.misc
  synapse/rest/client/room.py
Labels: T-Task, z-metrics

#13535 Time how long it takes us to do backfill processing
  changelog.d/13535.misc
  synapse/handlers/federation.py
  synapse/handlers/federation_event.py
Labels: T-Task, z-metrics

#13544 Add metrics to track rate limiter queue timing
  changelog.d/13544.misc
  synapse/util/ratelimitutils.py
Labels: T-Task, z-metrics

#13534 Add metrics to track how the rate limiter is affecting requests (sleep/reject)
  changelog.d/13534.misc
  synapse/util/ratelimitutils.py
Labels: T-Task, z-metrics

#13541 Track number of hosts affected by the rate limiter
  changelog.d/13541.misc
  synapse/util/ratelimitutils.py
Labels: T-Task, z-metrics

#13584 Fix Prometheus metrics being negative (mixed up start/end)
  changelog.d/13584.misc
  synapse/handlers/federation.py
  synapse/handlers/federation_event.py
  synapse/rest/client/room.py
Labels: T-Defect, z-metrics

#13600 Fix regression caused by #13573
  changelog.d/13600.misc
  synapse/storage/databases/main/roommember.py
Labels: X-Regression

#13588 Instrument `_check_sigs_and_hash_and_fetch` to trace time spent in child concurrent calls
  changelog.d/13588.misc
  synapse/crypto/event_signing.py
  synapse/events/spamcheck.py
  synapse/federation/federation_base.py
  synapse/federation/federation_client.py
Labels: T-Task, A-Messages-Endpoint

#13606 Use dedicated `get_local_users_in_room` to find local users when calculating `join_authorised_via_users_server` of a `/make_join` request
  changelog.d/13606.misc
  synapse/handlers/event_auth.py
Labels: T-Task

#13585 When loading current ids, sort by `stream_id` to avoid incorrect overwrite and avoid errors caused by sorting alphabetical instance name which can be `null`
  changelog.d/13585.bugfix
  synapse/storage/util/id_generators.py
Labels: T-Defect

#13608 Directly lookup local membership instead of getting all members in a room first (`get_users_in_room` mis-use)
  changelog.d/13608.misc
  synapse/handlers/events.py
  synapse/handlers/message.py
  synapse/handlers/room.py
  synapse/handlers/room_member.py
  synapse/server_notices/server_notices_manager.py
  synapse/storage/databases/main/roommember.py
  tests/rest/client/test_relations.py
Labels: T-Task

#13605 Update `get_users_in_room` mis-use to get hosts with dedicated `get_current_hosts_in_room`
  changelog.d/13605.misc
  synapse/handlers/device.py
  synapse/handlers/directory.py
  synapse/handlers/presence.py
  synapse/handlers/typing.py
  tests/federation/test_federation_sender.py
Labels: T-Task

#13586 Comment about a better future where we can get the state diff between two events
  changelog.d/13586.misc
  synapse/handlers/federation_event.py
Labels: T-Task

#13575 Optimize how we calculate `likely_domains` during backfill
  changelog.d/13575.misc
  synapse/handlers/federation.py
  synapse/handlers/room.py
  synapse/storage/controllers/state.py
  synapse/storage/databases/main/roommember.py
Labels: A-Performance, T-Task, A-Messages-Endpoint

#13649 Fix rate limit metrics registering twice and misreporting
  changelog.d/13649.bugfix
  synapse/server.py
  synapse/util/ratelimitutils.py
Labels: T-Defect, A-Metrics

#13658 Give the correct next event when the message timestamps are the same - MSC3030
  changelog.d/13658.bugfix
  synapse/storage/databases/main/events_worker.py
Labels: T-Defect

#13674 Remind people that direct TCP replication is deprecated.
  CHANGES.md
Labels: X-Release-Blocker
