Repository matrix-org/synapse, pull requests merged in 2022-07, with the labels that each got.

#13168 Fix stuck notification counts on small servers
  changelog.d/13168.bugfix
  synapse/storage/databases/main/event_push_actions.py
  tests/storage/test_event_push_actions.py
Labels: X-Release-Blocker

#13131 Fix application service not being able to join remote federated room without a profile set
  changelog.d/13131.bugfix
  synapse/handlers/room_member.py
Labels: A-Application-Service, T-Defect

#13197 Fix exception when using MSC3030 to look for remote federated events before room creation
  changelog.d/13197.bugfix
  synapse/handlers/room.py
Labels: T-Defect

#13332 Don't include appservice users when calculating push rules
  changelog.d/13332.bugfix
  synapse/push/bulk_push_rule_evaluator.py
  tests/push/test_push_rule_evaluator.py
Labels: X-Regression

#13320 Update `get_pdu` to return the original, pristine `EventBase`
  changelog.d/13320.misc
  synapse/federation/federation_client.py
  synapse/handlers/federation_event.py
  synapse/storage/databases/main/events.py
  tests/federation/test_federation_client.py
Labels: A-federation, T-Task

#13205 Backfill remote event fetched by MSC3030 so we can paginate from it later
  changelog.d/13205.feature
  synapse/handlers/federation_event.py
  synapse/handlers/room.py
Labels: T-Enhancement

#13346 Fix `get_pdu` asking every remote destination even after it finds an event
  changelog.d/13346.misc
  synapse/federation/federation_client.py
Labels: T-Task

#13370 Use stable prefixes for MSC3827: filtering of `/publicRooms` by room type
  changelog.d/13370.feature
  synapse/api/constants.py
  synapse/config/experimental.py
  synapse/handlers/room_list.py
  synapse/rest/client/versions.py
  synapse/storage/databases/main/room.py
  tests/rest/client/test_rooms.py
Labels: z-blocked
