Repository matrix-org/synapse, pull requests merged in 2022-11, with the labels that each got.

#14347 Fix typo in #13320 which could cause log spam
  changelog.d/14347.bugfix
  synapse/federation/federation_client.py
Labels: A-Logging, Z-Sentry

#14260 Implement MSC3912: Relation-based redactions
  changelog.d/14260.feature
  synapse/api/constants.py
  synapse/config/experimental.py
  synapse/handlers/message.py
  synapse/handlers/relations.py
  synapse/rest/client/room.py
  synapse/rest/client/versions.py
  synapse/storage/databases/main/relations.py
  tests/rest/client/test_redactions.py
  tests/rest/client/utils.py
Labels: Z-Time-Tracked

#14358 Update legacy `synapse_admin_mau:` metric names in docs
  changelog.d/14358.doc
  docs/usage/administration/monthly_active_users.md
Labels: X-Release-Blocker

#14448 Fix HTML templates missing correct HTML tags
  changelog.d/14448.bugfix
  synapse/res/templates/invalid_token.html
  synapse/res/templates/notif_mail.html
  synapse/res/templates/password_reset.html
  synapse/res/templates/password_reset_confirmation.html
  synapse/res/templates/password_reset_failure.html
  synapse/res/templates/password_reset_success.html
  synapse/res/templates/recaptcha.html
  synapse/res/templates/registration.html
  synapse/res/templates/registration_failure.html
  synapse/res/templates/registration_success.html
  synapse/res/templates/registration_token.html
  synapse/res/templates/sso_account_deactivated.html
  synapse/res/templates/sso_auth_account_details.html
  synapse/res/templates/sso_auth_bad_user.html
  synapse/res/templates/sso_auth_confirm.html
  synapse/res/templates/sso_auth_success.html
  synapse/res/templates/sso_error.html
  synapse/res/templates/sso_login_idp_picker.html
  synapse/res/templates/sso_new_user_consent.html
  synapse/res/templates/sso_redirect_confirm.html
  synapse/res/templates/terms.html
Labels: X-Release-Blocker, X-Regression

#14463 Revert "Remove slaved id tracker"
  changelog.d/14376.misc
  synapse/replication/slave/__init__.py
  synapse/replication/slave/storage/__init__.py
  synapse/replication/slave/storage/_slaved_id_tracker.py
  synapse/storage/databases/main/account_data.py
  synapse/storage/databases/main/devices.py
  synapse/storage/databases/main/events_worker.py
  synapse/storage/databases/main/push_rule.py
  synapse/storage/databases/main/pusher.py
  synapse/storage/databases/main/receipts.py
  synapse/storage/util/id_generators.py
Labels: X-Release-Blocker

#14477 Update forgotten references to legacy metrics in the included Grafana dashboard.
  changelog.d/14477.bugfix
  contrib/grafana/synapse.json
Labels: X-Release-Blocker

#14527 Optimize `filter_events_for_client` for faster `/messages` - v2
  changelog.d/14527.misc
  synapse/storage/databases/state/bg_updates.py
Labels: A-Performance, T-Enhancement, A-Messages-Endpoint

#14471 Move MSC3030 `/timestamp_to_event` endpoint to stable v1 location
  changelog.d/14471.feature
  docker/complement/conf/workers-shared-extra.yaml.j2
  docker/configure_workers_and_start.py
  docs/workers.md
  scripts-dev/complement.sh
  synapse/config/experimental.py
  synapse/federation/federation_client.py
  synapse/federation/transport/client.py
  synapse/federation/transport/server/__init__.py
  synapse/federation/transport/server/federation.py
  synapse/rest/client/room.py
  synapse/rest/client/versions.py
  tests/rest/client/test_rooms.py
Labels: A-Spec-Compliance, T-Task

#14575 Fix possible variable shadow in `create_new_client_event`
  changelog.d/14575.misc
  synapse/handlers/message.py
Labels: A-Create-Room

#14582 Revert "POC delete stale non-e2e devices for users (#14038)"
  changelog.d/14582.bugfix
  synapse/handlers/device.py
  synapse/storage/databases/main/devices.py
  tests/handlers/test_device.py
  tests/storage/test_client_ips.py
Labels: X-Release-Blocker
