Repository matrix-org/synapse, pull requests merged in 2022-01, with the labels that each got.

#11267 Correct Synapse install command for FreeBSD.
  changelog.d/11267.doc
  docs/setup/installation.md
Labels: X-Needs-Info

#11640 Improve Docker docs for use with Postgres
  changelog.d/11640.doc
  contrib/docker/docker-compose.yml
  docker/README.md
Labels: X-Awaiting-Changes

#11729 Fix a bug introduced in Synapse v1.0.0 whereby device list updates would not be sent to remote homeservers if there were too many to send at once.
  changelog.d/11729.bugfix
  synapse/storage/databases/main/devices.py
  tests/storage/test_devices.py
Labels: X-Release-Blocker

#11730 Fix a bug introduced in Synapse v1.50.0rc1 whereby outbound federation could fail because too many EDUs were produced for device updates.
  changelog.d/11730.bugfix
  synapse/storage/databases/main/devices.py
  tests/storage/test_devices.py
Labels: X-Release-Blocker

#11576 Remove the 'password_hash' from the Users Admin API endpoint response dictionary
  changelog.d/11576.feature
  docs/admin_api/user_admin_api.md
  synapse/handlers/admin.py
  synapse/rest/admin/users.py
  tests/rest/admin/test_user.py
Labels: Sponsored

#11775 Fix a bug that corrupted the cache of federated space hierarchies
  changelog.d/11775.bugfix
  synapse/federation/federation_client.py
  synapse/handlers/room_summary.py
  tests/handlers/test_room_summary.py
Labels: X-Release-Blocker

#11621 Remove account data (including client config, push rules and ignored users) upon user deactivation.
  changelog.d/11621.feature
  docs/admin_api/user_admin_api.md
  synapse/handlers/deactivate_account.py
  synapse/storage/databases/main/account_data.py
  tests/handlers/test_deactivate_account.py
Labels: Sponsored

#11743 Add a config flag to inhibit `M_USER_IN_USE` during registration
  changelog.d/11743.feature
  docs/sample_config.yaml
  synapse/config/registration.py
  synapse/handlers/register.py
  synapse/rest/client/register.py
  tests/rest/client/test_register.py
Labels: Sponsored

#11790 Add a module callback to set username at registration
  changelog.d/11790.feature
  docs/modules/password_auth_provider_callbacks.md
  synapse/handlers/auth.py
  synapse/module_api/__init__.py
  synapse/rest/client/register.py
  tests/handlers/test_password_providers.py
Labels: Sponsored

#11846 Configurable limits on avatars
  changelog.d/11846.feature
  docs/sample_config.yaml
  synapse/config/server.py
  synapse/handlers/profile.py
  synapse/handlers/room_member.py
  tests/handlers/test_profile.py
  tests/rest/client/test_profile.py
Labels: Sponsored
