Repository matrix-org/synapse, pull requests merged in 2022-06, with the labels that each got.

#12972 Prevent local quarantined media from being claimed by media retention
  changelog.d/12972.feature
  docs/usage/configuration/config_documentation.md
  synapse/rest/admin/media.py
  synapse/rest/media/v1/media_repository.py
  synapse/storage/databases/main/media_repository.py
  tests/rest/media/test_media_retention.py
Labels: Sponsored

#13023 Mention removed community/group worker endpoints in upgrade.md
  changelog.d/13023.doc
  docs/upgrade.md
Labels: X-Release-Blocker

#12893 Clean up schema for `event_edges`
  changelog.d/12893.misc
  synapse/storage/databases/main/events.py
  synapse/storage/databases/main/events_bg_updates.py
  synapse/storage/databases/main/purge_events.py
  synapse/storage/schema/__init__.py
  synapse/storage/schema/main/delta/71/01rebuild_event_edges.sql.postgres
  synapse/storage/schema/main/delta/71/01rebuild_event_edges.sql.sqlite
Labels: T-Task

#13011 Replace pyjwt with authlib in `org.matrix.login.jwt`
  changelog.d/13011.misc
  docs/jwt.md
  docs/usage/configuration/config_documentation.md
  poetry.lock
  pyproject.toml
  synapse/config/jwt.py
  synapse/rest/client/login.py
  tests/rest/client/test_login.py
Labels: X-Awaiting-Changes

#13035 Add custom well-known
  changelog.d/13035.feature
  docs/usage/configuration/config_documentation.md
  synapse/config/server.py
  synapse/rest/well_known.py
  tests/rest/test_well_known.py
Labels: X-Awaiting-Changes

#12944 Add Cross-Origin-Resource-Policy header to thumbnail and download media endpoints
  changelog.d/12944.misc
  synapse/http/server.py
  synapse/rest/media/v1/download_resource.py
  synapse/rest/media/v1/thumbnail_resource.py
  tests/rest/media/v1/test_media_storage.py
Labels: A-Media-Repository
