Repository matrix-org/synapse, pull requests merged in 2023-08, with the labels that each got.

#15754 Add configuration of the backoff algorithm for the federation client
  changelog.d/15754.misc
  docs/usage/configuration/config_documentation.md
  synapse/config/federation.py
  synapse/util/retryutils.py
  tests/storage/test_transactions.py
  tests/util/test_retryutils.py
Labels: Z-Time-Tracked

#15868 Remove old rows from the `cache_invalidation_stream_by_instance` table automatically. (This table is not used when Synapse is configured to use SQLite.)
  changelog.d/15868.feature
  synapse/storage/databases/main/cache.py
Labels: A-Database

#15870 Implements admin API to lock an user (MSC3939)
  changelog.d/15870.feature
  docs/admin_api/user_admin_api.md
  docs/usage/configuration/config_documentation.md
  synapse/_scripts/synapse_port_db.py
  synapse/api/auth/__init__.py
  synapse/api/auth/internal.py
  synapse/api/auth/msc3861_delegated.py
  synapse/api/errors.py
  synapse/config/user_directory.py
  synapse/handlers/admin.py
  synapse/handlers/user_directory.py
  synapse/rest/admin/users.py
  synapse/rest/client/logout.py
  synapse/storage/databases/main/registration.py
  synapse/storage/databases/main/user_directory.py
  synapse/storage/schema/main/delta/80/01_users_alter_locked.sql
  tests/api/test_auth.py
  tests/rest/admin/test_user.py
  tests/storage/test_registration.py
Labels: Z-Time-Tracked

#15891 Implements a task scheduler for resumable potentially long running tasks
  changelog.d/15891.feature
  synapse/app/generic_worker.py
  synapse/server.py
  synapse/storage/databases/main/__init__.py
  synapse/storage/databases/main/task_scheduler.py
  synapse/storage/schema/__init__.py
  synapse/storage/schema/main/delta/80/02_scheduled_tasks.sql
  synapse/types/__init__.py
  synapse/util/task_scheduler.py
  tests/util/test_task_scheduler.py
Labels: Z-Time-Tracked

#16127 Disallow user_consent where experimental MSC3861 is enabled
  changelog.d/16127.bugfix
  synapse/config/experimental.py
  tests/config/test_oauth_delegation.py
Labels: X-Release-Blocker

#16125 Add an admin endpoint to allow authorizing server to signal token revocations
  changelog.d/16125.misc
  synapse/api/auth/msc3861_delegated.py
  synapse/replication/tcp/client.py
  synapse/rest/admin/__init__.py
  synapse/rest/admin/oidc.py
  synapse/storage/databases/main/cache.py
  synapse/storage/databases/main/devices.py
  synapse/util/caches/expiringcache.py
  tests/handlers/test_oauth_delegation.py
  tests/replication/test_intro_token_invalidation.py
Labels: X-Release-Blocker

#16156 Properly update retry_last_ts when hitting the maximum retry interval
  changelog.d/16156.bugfix
  synapse/storage/databases/main/transactions.py
  tests/util/test_retryutils.py
Labels: X-Release-Blocker

#15816 Add configuration setting for CAS protocol version
  changelog.d/15816.feature
  docs/usage/configuration/config_documentation.md
  synapse/config/cas.py
  synapse/handlers/cas.py
Labels: z-auth
