Repository matrix-org/synapse, pull requests merged in 2023-09, with the labels that each got.

#16258 Revert MSC3861 introspection cache, admin impersonation and account lock
  changelog.d/16258.bugfix
  synapse/api/auth/msc3861_delegated.py
  synapse/replication/tcp/client.py
  synapse/rest/admin/__init__.py
  synapse/rest/admin/oidc.py
  synapse/storage/databases/main/cache.py
  synapse/storage/databases/main/devices.py
  synapse/util/caches/expiringcache.py
  tests/handlers/test_oauth_delegation.py
  tests/replication/test_intro_token_invalidation.py
Labels: X-Release-Blocker

#16278 Fix bug with new task scheduler using lots of CPU.
  changelog.d/16278.misc
  synapse/util/task_scheduler.py
Labels: X-Release-Blocker

#15488 Add automatic purge after all users forget a room
  changelog.d/15488.feature
  docs/usage/configuration/config_documentation.md
  synapse/app/generic_worker.py
  synapse/config/server.py
  synapse/handlers/pagination.py
  synapse/handlers/room.py
  synapse/handlers/room_member.py
  synapse/module_api/__init__.py
  synapse/rest/admin/__init__.py
  synapse/rest/admin/rooms.py
  tests/rest/admin/test_room.py
  tests/rest/admin/test_server_notice.py
  tests/rest/client/test_rooms.py
Labels: Z-Time-Tracked

#15691 Add developer documentation concerning gradual schema migrations with column alterations.
  changelog.d/15691.doc
  docs/development/database_schema.md
Labels: A-Docs, A-Database
