Repository matrix-org/synapse, pull requests merged in 2023-02, with the labels that each got.

#14949 Allow poetry-core 1.5.0
  changelog.d/14949.misc
  pyproject.toml
Labels: X-Awaiting-Changes

#14959 Clarify limitations of SRV delegation in documentation
  changelog.d/14959.doc
  docs/delegate.md
Labels: X-Awaiting-Changes

#15024 Fix bug in replication where response is cached
  changelog.d/15024.bugfix
  synapse/replication/http/_base.py
Labels: X-Release-Blocker

#15036 Bump schema version
  changelog.d/15036.misc
  synapse/storage/schema/__init__.py
Labels: X-Release-Blocker

#14892 Document how to start Synapse with Poetry
  changelog.d/14892.doc
  docs/workers.md
Labels: X-Awaiting-Changes

#15108 Teach portdb about `un_partial_stated_event_stream`
  changelog.d/15108.bugfix
  synapse/_scripts/synapse_port_db.py
Labels: X-Release-Blocker

#15114 Upper-bound frozendict dependency
  changelog.d/15114.misc
  poetry.lock
  pyproject.toml
Labels: X-Release-Blocker

#15143 Improve handling of non-ASCII characters in user directory search
  changelog.d/15143.misc
  synapse/storage/databases/main/user_directory.py
  tests/storage/test_user_directory.py
Labels: Z-Time-Tracked

#15150 Fix bug where 5s delays would occasionally happen.
  changelog.d/15150.bugfix
  synapse/replication/tcp/resource.py
  tests/replication/tcp/test_handler.py
Labels: X-Release-Blocker

#15116 Admin API endpoint to delete a reported event
  changelog.d/15116.feature
  docs/admin_api/event_reports.md
  synapse/rest/admin/event_reports.py
  synapse/storage/databases/main/room.py
  tests/rest/admin/test_event_reports.py
Labels: X-Awaiting-Changes
