Repository matrix-org/synapse, pull requests merged in 2023-01, with the labels that each got.

#14810 Calculate rooms changed for device lists to work.
  changelog.d/14810.bugfix
  synapse/api/filtering.py
  synapse/handlers/sync.py
Labels: X-Release-Blocker

#14817 Fix race calling `/members?at=`
  changelog.d/14817.bugfix
  synapse/storage/databases/main/stream.py
Labels: X-Release-Blocker

#14845 Fix missing field in AS documentation
  changelog.d/14845.doc
  docs/application_services.md
Labels: A-Application-Service, A-Docs, A-Config

#14839 Stabilise serving partial join responses
  changelog.d/14839.feature
  docker/complement/conf/workers-shared-extra.yaml.j2
  synapse/config/experimental.py
  synapse/federation/transport/server/federation.py
  tests/federation/test_federation_server.py
Labels: X-Release-Blocker

#14111 Change default room version to 10. Implements MSC3904
  changelog.d/14111.feature
  docs/usage/configuration/config_documentation.md
  synapse/config/server.py
  tests/rest/client/test_upgrade_room.py
Labels: Z-Spec-Blocked

#14872 Fix bug in wait for stream position
  changelog.d/14872.misc
  synapse/replication/tcp/client.py
Labels: X-Release-Blocker

#14881 Reduce max time we wait for stream positions
  changelog.d/14881.misc
  synapse/replication/http/_base.py
  synapse/replication/tcp/client.py
Labels: X-Release-Blocker

#14752 Enable Faster Remote Room Joins against worker-mode Synapse.
  changelog.d/14752.misc
  docker/complement/conf/workers-shared-extra.yaml.j2
  scripts-dev/complement.sh
  synapse/app/generic_worker.py
  synapse/handlers/device.py
  synapse/handlers/federation.py
  synapse/replication/tcp/streams/partial_state.py
  synapse/storage/databases/main/events_worker.py
  synapse/storage/databases/main/room.py
  synapse/storage/databases/main/state.py
Labels: X-Release-Blocker

#14914 Fix initialization of `_device_list_id_gen`
  changelog.d/14914.bugfix
  synapse/storage/databases/main/devices.py
Labels: X-Release-Blocker

#14917 Batch look-ups to see if rooms are partial stated.
  changelog.d/14917.misc
  synapse/handlers/sync.py
  synapse/storage/database.py
  synapse/storage/databases/main/room.py
Labels: X-Release-Blocker

#14677 Initial batch of notes on faster joins
  changelog.d/14677.doc
  docs/SUMMARY.md
  docs/development/synapse_architecture/faster_joins.md
Labels: X-Release-Blocker
