Repository matrix-org/synapse, pull requests merged in 2023-06, with the labels that each got.

#14213 Log when events are (unexpectedly) filtered out of responses in tests
  changelog.d/14213.misc
  docker/README.md
  docker/conf/log.config
  docker/configure_workers_and_start.py
  scripts-dev/complement.sh
  synapse/visibility.py
  tests/test_utils/logging_setup.py
Labels: T-Task, A-Testing

#15649 `N + 3`: Read from column `full_user_id` rather than `user_id` of tables `profiles` and `user_filters`
  changelog.d/15649.misc
  synapse/api/filtering.py
  synapse/handlers/account_validity.py
  synapse/handlers/admin.py
  synapse/handlers/auth.py
  synapse/handlers/deactivate_account.py
  synapse/handlers/profile.py
  synapse/handlers/register.py
  synapse/module_api/__init__.py
  synapse/push/mailer.py
  synapse/rest/client/filter.py
  synapse/rest/client/sync.py
  synapse/storage/databases/main/filtering.py
  synapse/storage/databases/main/profile.py
  synapse/storage/schema/__init__.py
  synapse/storage/schema/main/delta/78/01_validate_and_update_profiles.py
  synapse/storage/schema/main/delta/78/02_validate_and_update_user_filters.py
  tests/api/test_filtering.py
  tests/handlers/test_profile.py
  tests/module_api/test_api.py
  tests/rest/client/test_filter.py
  tests/storage/test_profile.py
Labels: A-Database

#15709 Some house keeping on `maybe_backfill()` functions
  changelog.d/15709.misc
  synapse/handlers/federation.py
Labels: A-Messages-Endpoint

#15721 Add context for when/why to use the `long_retries` option when sending Federation requests
  changelog.d/15721.misc
  synapse/http/matrixfederationclient.py
Labels: A-Federation, A-Docs, T-Task

#15725 Update error to more plainly explain we can only authorize our own events
  changelog.d/15725.misc
  synapse/federation/federation_server.py
Labels: A-Federation

#15650 Trace functions which return `Awaitable`
  changelog.d/15650.misc
  synapse/logging/opentracing.py
  tests/logging/test_opentracing.py
Labels: T-Enhancement

#15731 No need for the extra join since `membership` is built-in to `current_state_events`
  changelog.d/15731.misc
  synapse/storage/databases/main/roommember.py
Labels: T-Task, A-Database

#15738 Fix schema delta error in 1.85
  changelog.d/15738.bugfix
  synapse/storage/schema/main/delta/77/05thread_notifications_backfill.sql
Labels: X-Regression

#15695 Check required power levels earlier in createRoom handler.
  changelog.d/15695.bugfix
  synapse/handlers/room.py
  tests/rest/client/test_rooms.py
Labels: A-Create-Room

#15732 Remove redundant `room_memberships` join from admin FAQ to find participating servers in a room
  changelog.d/15732.doc
  docs/usage/administration/admin_faq.md
Labels: A-Docs, T-Task, A-Database

#15733 Remove superfluous `room_memberships` join from background update
  changelog.d/15733.misc
  synapse/storage/databases/main/roommember.py
Labels: T-Task, A-Database

#15746 Fix using TLS for replication
  changelog.d/15746.bugfix
  synapse/http/replicationagent.py
Labels: X-Regression

#15710 Backfill in the background if we're doing it "just because"
  changelog.d/15710.feature
  synapse/handlers/federation.py
Labels: A-Federation, A-Performance, T-Enhancement, A-Messages-Endpoint

#15737 Avoid backfill when we already have messages to return
  changelog.d/15737.feature
  synapse/handlers/pagination.py
Labels: A-Federation, A-Performance, T-Enhancement, A-Messages-Endpoint

#15772 Document `looping_call()` functionality that will wait for the given function to finish before scheduling another
  changelog.d/15772.doc
  synapse/util/__init__.py
Labels: A-Docs, T-Task

#15774 Fix empty scope when having version mismatch between workers
  changelog.d/15774.bugfix
  synapse/types/__init__.py
Labels: X-Release-Blocker

#15743 Regularly try to wake up dests instead of waiting for next PDU/EDU
  changelog.d/15743.misc
  synapse/federation/sender/__init__.py
  tests/federation/test_federation_catch_up.py
Labels: A-Federation, Z-Time-Tracked

#15748 Remove experimental MSC2716 implementation to incrementally import history into existing rooms
  changelog.d/15748.removal
  docker/complement/conf/workers-shared-extra.yaml.j2
  docker/configure_workers_and_start.py
  docs/workers.md
  scripts-dev/complement.sh
  synapse/api/constants.py
  synapse/api/room_versions.py
  synapse/app/generic_worker.py
  synapse/config/experimental.py
  synapse/event_auth.py
  synapse/events/__init__.py
  synapse/events/utils.py
  synapse/handlers/federation.py
  synapse/handlers/federation_event.py
  synapse/handlers/message.py
  synapse/handlers/room_batch.py
  synapse/handlers/room_member.py
  synapse/push/bulk_push_rule_evaluator.py
  synapse/rest/__init__.py
  synapse/rest/client/room_batch.py
  synapse/rest/client/versions.py
  synapse/server.py
  synapse/storage/databases/main/__init__.py
  synapse/storage/databases/main/event_federation.py
  synapse/storage/databases/main/events.py
  synapse/storage/databases/main/room_batch.py
  tests/rest/client/test_room_batch.py
  tests/storage/test_event_federation.py
Labels: T-Task

#15806 Switch from `matrix://` to `matrix-federation://` scheme for internal Synapse routing of outbound federation traffic
  changelog.d/15806.misc
  contrib/lnav/synapse-log-format.json
  scripts-dev/federation_client.py
  synapse/http/federation/matrix_federation_agent.py
  synapse/http/matrixfederationclient.py
  tests/federation/test_federation_client.py
  tests/http/federation/test_matrix_federation_agent.py
Labels: T-Task
