Repository matrix-org/synapse, pull requests merged in 2023-05, with the labels that each got.

#15224 Add config option to forget rooms automatically when users leave them
  changelog.d/15224.feature
  docs/usage/configuration/config_documentation.md
  synapse/config/room.py
  synapse/handlers/room_member.py
  synapse/handlers/room_member_worker.py
  synapse/server.py
  synapse/storage/databases/main/roommember.py
  synapse/storage/schema/main/delta/76/04_add_room_forgetter.sql
  tests/handlers/test_room_member.py
Labels: Z-Time-Tracked

#15569 Print full startup/initialization error
  changelog.d/15569.feature
  synapse/app/_base.py
Labels: T-Task

#15599 `traceback.format_exception(...)` usage that is compatible with Python 3.7 and 3.11
  changelog.d/15599.bugfix
  synapse/app/_base.py
Labels: T-Defect, X-Release-Blocker

#15604 Fix subscriptable type usage in Python <3.9
  changelog.d/15604.misc
  synapse/storage/controllers/stats.py
  tests/test_state.py
Labels: T-Task

#15602 Run mypy type checking with the minimum supported Python version
  changelog.d/15602.misc
  mypy.ini
Labels: T-Task, A-CI

#10428 Remove old R30 because R30v2 supercedes it
  changelog.d/10428.removal
  docs/usage/administration/monitoring/reporting_homeserver_usage_statistics.md
  synapse/app/phone_stats_home.py
  synapse/storage/databases/main/metrics.py
  tests/app/test_phone_stats_home.py
Labels: Z-Future-Maintenance, A-Metrics

#15633 Trace how many new events from the backfill response we need to process
  changelog.d/15633.misc
  synapse/handlers/federation_event.py
Labels: T-Task, A-Messages-Endpoint

#15610 Instrument `state` and `state_group` storage related things (tracing)
  changelog.d/15610.misc
  synapse/events/snapshot.py
  synapse/state/__init__.py
  synapse/storage/controllers/state.py
  synapse/storage/databases/state/bg_updates.py
  synapse/storage/databases/state/store.py
Labels: T-Task

#15636 Remove duplicate timestamp from test logs (`_trial_temp/test.log`)
  changelog.d/15636.misc
  tests/test_utils/logging_setup.py
Labels: A-Logging, T-Defect, A-Testing

#15578 Abstract worker connection details for HTTP Replication requests
  changelog.d/15578.misc
  synapse/http/client.py
  synapse/http/replicationagent.py
  synapse/replication/http/_base.py
Labels: A-Workers

#15647 Fix `@trace` not wrapping some state methods that return coroutines correctly
  changelog.d/15647.bugfix
  synapse/storage/controllers/state.py
Labels: T-Defect

#15585 Process previously failed backfill events in the background
  changelog.d/15585.feature
  synapse/handlers/federation_event.py
  synapse/storage/databases/main/event_federation.py
  synapse/util/iterutils.py
  tests/handlers/test_federation_event.py
  tests/storage/test_event_federation.py
Labels: A-Federation, A-Performance, T-Enhancement, A-Messages-Endpoint

#15668 Documentation improvements to contributing guide (#15667)
  changelog.d/15668.doc
  docs/development/contributing_guide.md
Labels: A-Docs, T-Enhancement, Z-Community-PR

#15674 Add Synapse version deploy annotations to Grafana dashboard
  changelog.d/15674.feature
  contrib/grafana/synapse.json
Labels: T-Enhancement, A-Metrics, Z-Dev-Wishlist
